### ISSUE TITLE
Suggestion - "time since bonus chest" timer

### ISSUE THREAD

**Issue by pon-Ch0** [sololegends/runelite-varlamore-house-thieving#10]
Hi, sorry if I put this suggestion in the wrong spot I have not done this before.  Would it be possible to get a "time since last bonus chest" timer within the overlay?

**Comment by sololegends** [comment]
Sure sure, should be easy enough.  

Real busy atm so might be a little while but I'll get it in there! Thanks for the suggestion ^.^

**Comment by sololegends** [comment]
Added it in will be in next update!

**Comment by pon-Ch0** [comment]
Thank you so much! I appreciate that, any chance i can send u a tip?

Thanks,
Jonathan
________________________________

**Comment by sololegends** [comment]
No problem ^.^ suggestions are always welcome!

I have the github sponsor thing setup, I think you can get a one-tip thing. 
I really appreciate you Jonathan <3
