### ISSUE TITLE
Distracted citizen alert spam

### ISSUE THREAD

**Issue by oeg91** [sololegends/runelite-varlamore-house-thieving#2]
Sometime i get spammed with the notification for the distracted citizen, it even slow down the runelite and freeze the game for a few seconds.
![image](https://github.com/sololegends/runelite-varlamore-house-thieving/assets/38496783/7948a42b-e235-415c-9d88-228ad7b5cdcb)

**Comment by sololegends** [comment]
For now, if that is a persistent problem, you can turn off the wealthy citizen notifications in the configuration panel until I get the update pushed and the Runelite plugin hub accepts the update
