### ISSUE TITLE
Timer going up indefinitely  when "Notify When Distracted" is off

### ISSUE THREAD

**Issue by claderoki** [sololegends/runelite-varlamore-house-thieving#3]
When the "Notify When Distracted" setting is off, the timer "Time since last distraction" keeps increasing without resetting:
![Screenshot from 2024-06-14 08-12-26](https://github.com/sololegends/runelite-varlamore-house-thieving/assets/49477117/022d6385-29b2-405c-a5ce-f9cffe4941bd)

**Comment by claderoki** [comment]
I notice that after leaving the area and coming back the overlay is gone completely, so I guess this only happens if you disable the setting while thieving with the overlay on. 

It would be nice, imo, if the overlay was still shown regardless of whether you receive a notification or not. I personally prefer using the in-game audio cues instead of OS notifications

**Comment by sololegends** [comment]
Interesting, correct me if I'm wrong, but the sequence of events seems to be:
1. Turn on Notify When Distracted
2. Stand in the town square 
3. Turn off Notify When Distracted
4. Observe the timer never resetting after

I can look at adding an audio cue instead of OS notification as a general "notification type" drop down. 
Would that be what you're looking for, or would you look for  individual control for each notification type?

**Comment by claderoki** [comment]
Yes, that's the correct sequence on how to reproduce this :) 

What I meant by audio cue is that there's already a built-in audio cue that I prefer using, hence why I disabled notifications. I suppose it would be nice if the overlay would remain functioning normally regardless of notification setting. 

Thank you for your response!

**Comment by sololegends** [comment]
Awesome! Should be an easy fix :) 

Ohh so the little jingle for the bonus chests right and the whistle for home owner returning? 
I don't recall an audio cue for the distractions but I may be miss remembering, Haven't been back to Varlamore thieving for a few weeks. 

So in essence just an "enable panel" option separate from the notifications options for better choice correct?

I love when people submit issues to help me make my plugins better ^.^ so thank you for reaching out!

**Comment by claderoki** [comment]
Thank you! I think that'd be a great solution. I'd appreciate that a lot. Thank you for the plugin, it works very well!

**Comment by sololegends** [comment]
Preview of the new configuration options: 

![image](https://github.com/sololegends/runelite-varlamore-house-thieving/assets/10588645/ecec5ad3-7de1-49ff-9110-d88c0ccf3652)

**Comment by sololegends** [comment]
Updates done and tested. Waiting on Runelite Devs to approve Pull request.

https://github.com/runelite/plugin-hub/pull/6168

**Comment by claderoki** [comment]
It looks great, thanks a lot!
