### ISSUE TITLE
Add option to disable sound when receiving blessed bone statue or jewlery

### ISSUE THREAD

**Issue by Mike-Dunton** [sololegends/runelite-varlamore-house-thieving#4]
Would be nice to add a config option that prevented the sound from paying when you receive a blessed bone statue or jewelry, so you don't get distracted from what you are doing while you afk thieving.

**Comment by sololegends** [comment]
That's a great idea! 

I've not yet done anything removing or interacting with sounds on Runelite so I'll have to investigate the possibilities. If you can link any plugins that do something similar, removing sounds, that would be wonderful 😊
