### ISSUE TITLE
Request: Option to show distraction timer while inside houses as well

### ISSUE THREAD

**Issue by Matkatamiba** [sololegends/runelite-varlamore-house-thieving#5]
For min/maxing, it could be nice to have a checkbox to show the outside distraction timer even while you're inside the houses, so you could hop out of Lavinia's house and get the 20 seconds of turbo pickpocketing, which maybe would be slightly faster overall xp and a way to keep re-upping your keys while running laps.

**Comment by sololegends** [comment]
Sound be a pretty easy add. 

I'll likely make it a select field for one, the other, or both whilst inside a house. 

I'll also make the distraction notification able to be toggles inside the house as well. 

Thanks for the suggestion :)
