### ISSUE TITLE
Bonus Chest

### ISSUE THREAD

**Issue by ZpandemicZ** [sololegends/runelite-varlamore-house-thieving#6]
Hey, 

Just wanted to let you know that when thieving in the houses the indicator to show which thieving chest rewards the limited bonus xp sometimes flashes for half a game tick or not at all

Have tried resetting the plugin, removing and reinstalling as well but still the same issue.

Thanks

**Comment by ZpandemicZ** [comment]
some reason its started to work as normal now

**Comment by Mythirion** [comment]
This is happening to me too. Makes it really hard to catch exactly which chest has the bonus loot.

**Comment by sololegends** [comment]
Alrighty, I'll take a look at this

**Comment by sololegends** [comment]
I couldn't replicate the issue but I made some changes I believe will make that issue impossible going forward 

https://github.com/runelite/plugin-hub/pull/6577

**Comment by ZpandemicZ** [comment]
Too easy,
The issue happened at time of reporting but it came good eventually

Regards,

Ben

On 11 Sep 2024, at 9:42 AM, Benjamin Z ***@***.***> wrote:

﻿

I couldn't replicate the issue but I made some changes I believe will make that issue impossible going forward

runelite/plugin-hub#6577<https://github.com/runelite/plugin-hub/pull/6577>
