### ISSUE TITLE
Notification Updates

### ISSUE THREAD

**Issue by NicholasMoser** [sololegends/runelite-varlamore-house-thieving#8]
Hello,

I'm looking into adding notification updates to this plugin, primarily:

1. Flashing the screen red
2. Displaying notifications even when focused

I see in the code how to make this change and I am willing to do so. I just don't really know how to test. Do you have to build runelite locally or can you import a snapshot build of this into runelite?

Thanks

**Comment by coupe-1** [comment]
![RuneLite_kCV9ysOarl](https://github.com/user-attachments/assets/2df8308d-796f-4505-aff6-f52a16a32821)

You can do this using the "RuneLite" plugin notification settings.

**Comment by NicholasMoser** [comment]
Oh! I was not aware, that's much easier :)

Thank you.
